name: Update PresentMon

on:
  # schedule:
  #   - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-presentmon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Update PresentMon
        run: node ./presentmon/updatePresentMon.js

      - name: Commit new version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update PresentMon
          file_pattern: "presentmon/presentmon.zip presentmon/version"
